#!/bin/sh
# See LICENSE file for copyright and license details.

usage() {
	echo "usage: phrenamer [-dh] [DIR]"
	exit 1
}

case "$1" in
	'-d') dry="t" ;;
	-*) usage ;;
	*) dir="$1" ;;
esac

[ "$dry" ] && dir="$2"
! [ "$dir" ] && dir="."

files=$(find "$dir" -regextype posix-extended -regex '.*\.(jpg|JPG|jpeg)')

digits=$(echo "$files" | wc -l | wc -c)
zeroes=$((digits-1)) # minus '\0'

IFS="
"
count=0
for fname in $files; do
	count=$((count+1))
	newname="$dir/$(printf %0${zeroes}d $count).jpg"
	echo "$fname -> $newname"
	! [ -f "$newname" ] && [ -z "$dry" ] && mv "$fname" "$newname"
done

