#!/bin/sh
# See LICENSE file for copyright and license details.

die() {
	echo "$1" >&2
	exit 1
}

usage() {
	die 'usage: phrenamer [-d] [dir]'
}

while getopts :d opt; do
	case "$opt" in
	d)	dry='t' ;;
	?)	usage ;;
	esac
done

shift $((OPTIND - 1))
dir="${1:-$(pwd)}"

files=$(ls "${dir}/"*.jpg "${dir}"/*.jpeg "${dir}/"*.JPG 2> /dev/null)
! [ "$files" ] && die 'Error: no files to rename.'

filenum=$(echo "$files" | wc -l)
zeroes=$((${#filenum} - 1)) # minus '\0'

IFS="
"
count=0
for fname in $files; do
	count=$((count + 1))
	dirpart=$(dirname "$fname")
	newname=$(printf "%s/%0${zeroes}d.jpg" "$dirpart" "$count")
	echo "$fname -> $newname"
	! [ -f "$newname" ] && [ -z "$dry" ] && mv "$fname" "$newname"
done

